#!/usr/bin/env python3
"""
Ploan MCP Server — exposes terminal theming tools to AI agents.

The AI agent generates color palettes, SVG backgrounds, and CSS.
Ploan receives those assets and applies them to the running terminal,
TUI, and Web UI.

MCP Protocol: JSON-RPC 2.0 over stdio.

Compatible with: OpenCode, Claude Code, Grok Build, open-interpreter.
"""

import json
import sys
import os
import traceback
from typing import Any

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from Ploan_skill import (
    customize_environment,
    detect_terminal,
    restore_terminal_state,
    apply_terminal_colors,
    save_terminal_state,
    THEME_PRESETS,
    ColorPalette,
)

MCP_VERSION = "2024-11-05"
SERVER_NAME = "ploan"
SERVER_VERSION = "0.2.0"


def log(msg: str) -> None:
    print(f"[ploan-mcp] {msg}", file=sys.stderr, flush=True)


def send_response(response: dict) -> None:
    sys.stdout.write(json.dumps(response) + "\n")
    sys.stdout.flush()


def handle_initialize(msg_id: Any, params: dict) -> None:
    send_response({
        "jsonrpc": "2.0",
        "id": msg_id,
        "result": {
            "protocolVersion": MCP_VERSION,
            "capabilities": {"tools": {}},
            "serverInfo": {
                "name": SERVER_NAME,
                "version": SERVER_VERSION,
            },
        },
    })


def handle_list_tools(msg_id: Any) -> None:
    send_response({
        "jsonrpc": "2.0",
        "id": msg_id,
        "result": {
            "tools": [
                {
                    "name": "customize_environment",
                    "description": (
                        "Apply a terminal theme generated by the AI agent. "
                        "The AI provides a complete color palette, optional "
                        "SVG background image, opacity value, and TUI theme name. "
                        "Ploan applies these to the running terminal, TUI, and Web UI. "
                        "Use get_terminal_info first to detect the terminal type and "
                        "capabilities before generating the theme assets."
                    ),
                    "inputSchema": {
                        "type": "object",
                        "properties": {
                            "palette": {
                                "type": "object",
                                "description": (
                                    "Complete 16-color ANSI palette with semantic colors. "
                                    "Fields: name (string), color0 through color15 (hex strings like '#1a1b26'), "
                                    "background (hex), foreground (hex), cursor (hex), accent (hex). "
                                    "Generate these colors based on the user's theme description."
                                ),
                                "properties": {
                                    "name": {"type": "string"},
                                    "color0": {"type": "string"}, "color1": {"type": "string"},
                                    "color2": {"type": "string"}, "color3": {"type": "string"},
                                    "color4": {"type": "string"}, "color5": {"type": "string"},
                                    "color6": {"type": "string"}, "color7": {"type": "string"},
                                    "color8": {"type": "string"}, "color9": {"type": "string"},
                                    "color10": {"type": "string"}, "color11": {"type": "string"},
                                    "color12": {"type": "string"}, "color13": {"type": "string"},
                                    "color14": {"type": "string"}, "color15": {"type": "string"},
                                    "background": {"type": "string"},
                                    "foreground": {"type": "string"},
                                    "cursor": {"type": "string"},
                                    "accent": {"type": "string"},
                                },
                            },
                            "background_svg": {
                                "type": "string",
                                "description": (
                                    "SVG markup to render as the terminal background image. "
                                    "Keep it simple and abstract — ~800x600, matching the theme's energy. "
                                    "Use gradients that blend with the background color."
                                ),
                            },
                            "opacity": {
                                "type": "number",
                                "description": "Terminal window opacity (0.0 = transparent, 1.0 = solid). Typical range: 0.85-0.95.",
                            },
                            "tui_theme": {
                                "type": "string",
                                "description": (
                                    "TUI theme name to set for the host AI CLI. "
                                    "For OpenCode: one of 'opencode', 'catppuccin', 'dracula', 'flexoki', "
                                    "'gruvbox', 'monokai', 'onedark', 'tokyonight', 'tron'. "
                                    "For Grok Build: one of 'groknight', 'grokday', 'tokyonight', "
                                    "'rosepine-moon', 'oscura-midnight', 'auto'."
                                ),
                            },
                            "theme_name": {
                                "type": "string",
                                "description": "Human-readable name for the generated theme (e.g. 'Cyberpunk Ocean').",
                            },
                            "save_state": {
                                "type": "boolean",
                                "description": "Save current terminal state before applying (for restore). Default: true.",
                                "default": True,
                            },
                        },
                    },
                },
                {
                    "name": "get_terminal_info",
                    "description": (
                        "Detect the current terminal emulator, OS, and color support level. "
                        "The AI should call this BEFORE generating a theme, so the generated "
                        "assets are compatible with the user's terminal capabilities."
                    ),
                    "inputSchema": {
                        "type": "object",
                        "properties": {},
                    },
                },
                {
                    "name": "restore_environment",
                    "description": (
                        "Restore the terminal to its state before the last Ploan theme was applied. "
                        "Resets colors, background image, and opacity to their original values."
                    ),
                    "inputSchema": {
                        "type": "object",
                        "properties": {},
                    },
                },
                {
                    "name": "list_themes",
                    "description": (
                        "List built-in theme presets the AI can use as starting points "
                        "or reference when generating custom palettes."
                    ),
                    "inputSchema": {
                        "type": "object",
                        "properties": {},
                    },
                },
            ],
        },
    })


def handle_call_tool(msg_id: Any, tool_name: str, arguments: dict) -> None:
    try:
        if tool_name == "get_terminal_info":
            terminal = detect_terminal()
            info = {
                "terminal": terminal,
                "os": sys.platform,
                "shell": os.environ.get("SHELL", "unknown"),
                "has_truecolor": os.environ.get("COLORTERM") == "truecolor",
                "supported_terminals_for_background_image": [
                    "kitty", "alacritty", "gnome_terminal",
                ],
                "supported_terminals_for_opacity": [
                    "kitty", "gnome_terminal",
                ],
                "supported_terminals_for_colors": [
                    "kitty", "alacritty", "ghostty", "foot", "wezterm",
                    "konsole", "gnome_terminal", "windows_terminal",
                ],
                "note": (
                    "If terminal is 'unknown', the server is running in a subprocess "
                    "(e.g. from an AI CLI tool). Colors can still be applied via OSC "
                    "escape sequences on most terminals."
                ),
            }
            send_response({
                "jsonrpc": "2.0",
                "id": msg_id,
                "result": {"content": [{"type": "text", "text": json.dumps(info, indent=2)}]},
            })

        elif tool_name == "customize_environment":
            palette_data = arguments.get("palette")
            background_svg = arguments.get("background_svg")
            opacity = arguments.get("opacity")
            tui_theme = arguments.get("tui_theme")
            theme_name = arguments.get("theme_name")
            save_state = arguments.get("save_state", True)

            log(f"Applying theme: {theme_name or 'custom'} (tui={tui_theme}, opacity={opacity})")

            result = customize_environment(
                palette_json=palette_data,
                theme_name=theme_name,
                background_svg=background_svg,
                opacity=opacity,
                tui_theme=tui_theme,
                save_state=save_state,
            )

            text = f"**{result.theme_name}**\n\n"
            text += f"- Terminal: `{result.terminal}` — "
            if result.terminal_colors_applied:
                text += "colors applied\n"
            else:
                text += "colors applied via OSC fallback\n"

            if result.background_image_applied:
                text += "- Background image set\n"
            if result.opacity_applied:
                text += f"- Opacity set to {opacity}\n"
            if result.tui_theme_applied:
                text += f"- TUI theme set to `{tui_theme}`\n"

            text += f"\n{result.message}"

            send_response({
                "jsonrpc": "2.0",
                "id": msg_id,
                "result": {"content": [{"type": "text", "text": text}]},
            })

        elif tool_name == "restore_environment":
            log("Restoring terminal state...")
            ok, msg = restore_terminal_state()
            send_response({
                "jsonrpc": "2.0",
                "id": msg_id,
                "result": {"content": [{"type": "text", "text": f"{'✓' if ok else '✗'} {msg}"}]},
            })

        elif tool_name == "list_themes":
            themes_list = "\n".join(
                f"- **{name}** — {palette.name} "
                f"(bg: {palette.background}, fg: {palette.foreground}, accent: {palette.accent})"
                for name, palette in THEME_PRESETS.items()
            )
            send_response({
                "jsonrpc": "2.0",
                "id": msg_id,
                "result": {
                    "content": [{
                        "type": "text",
                        "text": (
                            "Built-in Ploan theme presets (use as reference or starting points):\n\n"
                            f"{themes_list}\n\n"
                            "When generating a custom palette, use these color schemes as inspiration "
                            "but create your own unique colors based on the user's description."
                        ),
                    }],
                },
            })

        else:
            send_response({
                "jsonrpc": "2.0",
                "id": msg_id,
                "error": {"code": -32601, "message": f"Unknown tool: {tool_name}"},
            })

    except Exception as e:
        log(f"Error calling tool {tool_name}: {e}")
        log(traceback.format_exc())
        send_response({
            "jsonrpc": "2.0",
            "id": msg_id,
            "result": {
                "content": [{"type": "text", "text": f"Error: {e}"}],
                "isError": True,
            },
        })


def handle_notifications(method: str) -> bool:
    if method in ("notifications/initialized", "initialized"):
        log("MCP initialized successfully")
        return True
    return False


def main():
    log("Ploan MCP server v0.2.0 starting...")

    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue

        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            log(f"Invalid JSON received: {line[:100]}")
            continue

        msg_id = msg.get("id")
        method = msg.get("method", "")
        params = msg.get("params", {})

        if method == "initialize":
            handle_initialize(msg_id, params)
        elif method == "tools/list":
            handle_list_tools(msg_id)
        elif method == "tools/call":
            tool_name = params.get("name", "")
            arguments = params.get("arguments", {})
            handle_call_tool(msg_id, tool_name, arguments)
        elif handle_notifications(method):
            pass
        elif msg_id is not None:
            send_response({
                "jsonrpc": "2.0",
                "id": msg_id,
                "error": {"code": -32601, "message": f"Method not found: {method}"},
            })
        else:
            log(f"Ignoring unknown notification: {method}")


if __name__ == "__main__":
    main()
